name: bag_finder_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    assets:
      - assets/images/
    sdk: flutter
  flutter_modular: ^6.3.4
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dio: ^5.4.2+1
  dartz: ^0.10.1
  uno: ^1.1.9
  logger: ^2.2.0
  provider: ^6.1.2
  mockito: ^5.4.4
  build_runner: ^2.4.9
  dropdown_button2: ^2.3.9
  intl: 0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  file_picker: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.7.0
  connectivity_plus: ^6.0.3
  geocoding: ^3.0.0
  image_picker: ^1.1.2

flutter:
  uses-material-design: true
