name: bag_finder_frontend
description: "Bag Finder"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.4.0
  flutter_modular: ^6.3.4
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.2.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/flying-around.png
    - images/group-interrogation.png
    - images/luggage-two-persons.png
    - images/paper-macute.png
    - images/two-persons.png
